# Environment variables
email: 'stevenadema@gmail.com'
password: 'Another.1'
location: 'Taggart Family Y'
preferred_time_slot: '10:00 AM' # must match value from timeslots_dict below
second_choice_slot: '6:00 PM'
chrome_driver_path: 'C:\Program Files\Google\chromedriver.exe'

# Weekday time slots (Weekend timeslots unavailable after 2:00 PM)
timeslots_dict:
  '7:00 AM': 1
  '8:00 AM': 2
  '9:00 AM': 3
  '10:00 AM': 4
  '11:00 AM': 5
  '12:00 PM': 6
  '1:00 PM': 7
  '2:00 PM': 8
  '3:00 PM': 9
  '4:00 PM': 10
  '5:00 PM': 11
  '6:00 PM': 12
